# Generated by Django 5.0.2 on 2024-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_authuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('bookedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
