# Generated by Django 5.0.2 on 2024-02-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='bookedFor',
            field=models.CharField(default='Dr', max_length=20),
        ),
        migrations.AddField(
            model_name='authuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=12),
        ),
    ]
