# Generated by Django 5.0.2 on 2024-02-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_appointments_bookedfor_authuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=20)),
                ('doctorName', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
