# Generated by Django 5.0.2 on 2024-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_authuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='hospital',
            field=models.CharField(default='hospital', max_length=150),
        ),
    ]
