# Generated by Django 5.0.2 on 2024-03-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_doctorlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorlist',
            name='image',
        ),
    ]
